#:schema node_modules/wrangler/config-schema.json
name = "test-drizzle-durable-objects"

workers_dev = true
main = "./build/index.js"
compatibility_date = "2024-09-26"

[assets]
directory = "./public"

[observability]
enabled = false

[[durable_objects.bindings]]
name = "DO"
class_name = "DrizzleTestDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DrizzleTestDO"]
